version: '3.8'

services:
  web:
    build:
      context: .  # The current directory
      dockerfile: Dockerfile  # Ensure this matches the exact filename of your Dockerfile
    ports:
      - "80:80"  # Map container port 80 to host port 80
    volumes:
      - .:/usr/share/nginx/html  # Mount current directory to the Nginx container directory
    restart: always  # Optionally restart the container if it fails
