version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile  # Specify the Dockerfile if it's named differently
    ports:
      - "80:80"  # Expose port 80 of the container to port 80 on the host
    volumes:
      - .:/usr/share/nginx/html  # Mount current directory to the Nginx web server directory
    restart: always  # Optional: Restart the container if it fails
